services:
  trip-planner-db:
    image: postgis/postgis:17-3.5-alpine
    container_name: trip-planner-db
    environment:
      POSTGRES_DB: ${TRIP_PLANNER_POSTGRES_DB}
      POSTGRES_USER: ${TRIP_PLANNER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TRIP_PLANNER_POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - trip-planner-data:/var/lib/postgresql/data
      #- ./init-scripts:/docker-entrypoint-initdb.d #???
    networks:
      - pullapp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TRIP_PLANNER_POSTGRES_USER} -d ${TRIP_PLANNER_POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  accounts-db:
    image: postgres:17-alpine
    container_name: accounts-db
    environment:
      POSTGRES_USER: ${ACCOUNTS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ACCOUNTS_POSTGRES_PASSWORD}
      POSTGRES_DB: ${ACCOUNTS_POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - accounts-data:/var/lib/postgresql/data
    networks:
      - pullapp-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${ACCOUNTS_POSTGRES_USER} -d ${ACCOUNTS_POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  cache:
    image: redis:8-alpine
    container_name: cache
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - ./cache/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    networks:
      - pullapp-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  compute-queue:
    image: rabbitmq:4.2-management-alpine
    container_name: compute-queue
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
      RABBITMQ_DEFAULT_VHOST: /
      RABBITMQ_PLUGINS: "rabbitmq_management rabbitmq_prometheus"
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    volumes:
      - ./compute-queue/definitions.json:/etc/rabbitmq/definitions.json
      #- ./compute-queue/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - pullapp-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  route-calc-tests:
    build:
      context: ../services/route-calc
      dockerfile: Dockerfile.test
    container_name: route-calc-tests
    depends_on:
      compute-queue:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: compute-queue
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
    volumes:
      - ../services/route-calc:/app
    networks:
      - pullapp-network
    command: pytest tests/rabbitmq_integration_test.py -v
    profiles:
      - tests

networks:
  pullapp-network:
    driver: bridge

volumes:
  trip-planner-data:
  accounts-data:
  redis-data:
  rabbitmq-data:
