services:
  gateway:
    environment:
      - Jwt__Key=${ACCOUNTS_JWT_SECRETKEY}
      - Jwt__Issuer=pullapp
      - Jwt__Audience=pullapp
    build:
      context: ./src/services/gateway
      dockerfile: Dockerfile
      args:
        - BUILD_MODE=Debug # TODO
    ports:
      - "5000:8080"
    networks:
      - gateway-network
    depends_on:
      - accounts-api
  
  accounts-api:
    build:
      context: ./src/services/accounts
      dockerfile: Dockerfile
      args:
        - BUILD_MODE=Debug # TODO
    environment:
      - ASPNETCORE_ENVIRONMENT=Development # TODO
      - ConnectionStrings__DefaultConnection=Host=accounts-db;Database=${ACCOUNTS_POSTGRES_DB};Username=${ACCOUNTS_POSTGRES_USER};Password=${ACCOUNTS_POSTGRES_PASSWORD};GSS Encryption Mode=Disable
      - Jwt__SecretKey=${ACCOUNTS_JWT_SECRETKEY}
      - Jwt__Issuer=pullapp
      - Jwt__Audience=pullapp
      - Logging__LogLevel__Microsoft.AspNetCore.Authentication=Debug
      - Logging__LogLevel__Microsoft.AspNetCore.Authorization=Debug
    depends_on:
      accounts-db:
        condition: service_healthy
    networks:
      - gateway-network
      - accounts-network

  accounts-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${ACCOUNTS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ACCOUNTS_POSTGRES_PASSWORD}
      POSTGRES_DB: ${ACCOUNTS_POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${ACCOUNTS_POSTGRES_USER} -d ${ACCOUNTS_POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - accounts-network
    ports:
      - "5432:5432" # TODO development only!

  trip-planner-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development # TODO
      - TripPlannerDb__Host=trip-planner-db
      - TripPlannerDb__Database=${TRIP_PLANNER_POSTGRES_DB}
      - TripPlannerDb__Username=${TRIP_PLANNER_POSTGRES_USER}
      - TripPlannerDb__Password=${TRIP_PLANNER_POSTGRES_PASSWORD}
      - ComputeQueue__Host=
    build:
      context: ./src
      dockerfile: services/trip-planner/Dockerfile
    networks:
      - gateway-network
      - trip-planner-network

  trip-planner-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${TRIP_PLANNER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TRIP_PLANNER_POSTGRES_PASSWORD}
      POSTGRES_DB: ${TRIP_PLANNER_POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${TRIP_PLANNER_POSTGRES_USER} -d ${TRIP_PLANNER_POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - trip-planner-network
    ports:
      - "5433:5432" # TODO development only!

  frontend-web:
    build:
      context: src/frontend/pullapp-frontend
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000" # TODO development only!
    networks:
      - gateway-network
    environment:
      - NEXT_PUBLIC_API_URL=http://gateway:8080 # adres Gatewaya wewnątrz sieci Dockera

networks:
  gateway-network:
  accounts-network:
  trip-planner-network:
