chat-db:
    image: mongo:8-noble
    container_name: chat-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${CHAT_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${CHAT_MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${CHAT_MONGO_DB}
    ports:
      - "27017:27017"
    volumes:
      - chat-db-data:/data/db
    networks:
      - pullapp-network
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
