apiVersion: v1
kind: Service
metadata:
  name: accounts
  labels:
    app: accounts
spec:
  selector:
    app: accounts
  ports:
  - port: 80
    targetPort: 8080
    name: http
    protocol: TCP
  type: ClusterIP