FROM python:3.14-slim

ENV PYTHONUNBUFFERED=1
ENV POETRY_VIRTUALENVS_CREATE=false
ENV POETRY_VERSION=2.1.4

WORKDIR /app

RUN apt-get update && apt-get install -y \
    curl \
    build-essential \
    cmake \
    libcurl4-openssl-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install "poetry==$POETRY_VERSION"
COPY pyproject.toml poetry.lock* ./

RUN poetry install --no-interaction --no-ansi --no-root

COPY route_calc/ ./route_calc/
COPY tests/ ./tests/
COPY CMakeLists.txt .
COPY cpp ./cpp/

# Install package (Python models/protobuf); C++ extension built via scikit-build
RUN poetry install --no-interaction --no-ansi

CMD ["pytest", "tests/rabbitmq_e2e_test.py", "-v"]
