apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pullapp

resources:
  - namespace.yaml
  - services/trip-planner/deployment.yaml
  - services/trip-planner/service.yaml
  - services/route-calc/deployment.yaml
  - services/route-calc/service.yaml
  - services/route-calc/scaled-object.yaml
  - services/accounts/deployment.yaml
  - services/accounts/service.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: pullapp

images:
  - name: trip-planner
    newName: pullapp/trip-planner
  - name: route-calc
    newName: pullapp/route-calc
  - name: accounts
    newName: pullapp/accounts
  - name: gateway
    newName: pullapp/gateway

configMapGenerator:
- name: trip-planner-config
  files:
  - services/trip-planner/appsettings.json
- name: route-calc-config
  files:
  - services/route-calc/config.json