@Host = http://localhost:5000

###
POST {{Host}}/api/route
Content-Type: application/json

{
  "driverId": "11111111-1111-1111-1111-111111111111",
  "start": "A",
  "end": "B"
}

###
GET {{Host}}/api/route/eb571622-3167-464a-b7be-f09e5a5fbd39