name: CI pipeline for accounts service

# We only want to run this CI pipeline for changes to the accounts service
on:
  push:
    branches: [ master ]
    paths:
      - 'src/services/accounts/**'
      - '.github/workflows/accounts-ci.yaml'
  pull_request:
    paths:
      - src/accounts/**'

env:
  BUILD_ID: ${{ github.run_id }}-${{ github.run_number }}
  COMMIT_SHA: ${{ github.sha }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/services/accounts
    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0

      - name: Cache packages
        uses: actions/cache@v5
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Restore
        run: dotnet restore

      - name: Run unit tests
        run: |
            dotnet test \
            --configuration Release

  dockerize:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/services/accounts
    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0

      - name: Cache packages
        uses: actions/cache@v5
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release
      
      - name: Docker build
        run: docker build -f Dockerfile -t accounts:${{ env.COMMIT_SHA }} .