name: CI pipeline for route-calc service

# We only want to run this CI pipeline for changes to the route-calc service
on:
  push:
    branches: [ master ]
    paths:
      - 'src/services/route-calc/**'
      - '.github/workflows/route-calc-ci.yaml'
  pull_request:
    paths:
      - 'src/services/route-calc/**'

env:
  BUILD_ID: ${{ github.run_id }}-${{ github.run_number }}
  COMMIT_SHA: ${{ github.sha }}

jobs:
  build-test-docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/services/route-calc

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Generate protoc
        run: |
          mkdir -p src/route_calc/generated
          protoc --proto_path=../../schemas/pullapp/core/v1/ --python_out=src/route_calc/generated/ ../../schemas/pullapp/core/v1/queue.proto

      - name: Install Poetry
        run: pip install poetry
      
      - name: Configure Poetry
        run: poetry config virtualenvs.in-project true
      
      - uses: actions/cache@v4
        with:
          path: .venv
          key: poetry-${{ runner.os }}-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            poetry-${{ runner.os }}-

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Run tests
        run: poetry run pytest
      
      - name: Docker build
        run: docker build -f Dockerfile -t route-calc:${{ env.COMMIT_SHA }} .