name: CI pipeline for route-calc service

# We only want to run this CI pipeline for changes to the route-calc service
on:
  push:
    branches: [ master ]
    paths:
      - 'src/services/route-calc/**'
      - '.github/workflows/route-calc-ci.yaml'
  pull_request:
    paths:
      - src/route-calc/**'

env:
  BUILD_ID: ${{ github.run_id }}-${{ github.run_number }}
  COMMIT_SHA: ${{ github.sha }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/services/route-calc
    steps:
      - uses: actions/checkout@v6.0.2

    # todo
  dockerize:
    needs: build-and-test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/services/route-calc
    steps:
      - uses: actions/checkout@v6.0.2
      
      - name: Docker build
        run: docker build -f infra/docker/Dockerfile -t route-calc:${{ env.COMMIT_SHA }} .
      
        
      