flyway.url=jdbc:postgresql://localhost:5432/trip_planner
flyway.user=app
flyway.password=password
flyway.locations=filesystem:./migrations
flyway.sqlMigrationSuffix=.sql
flyway.baselineOnMigrate=true


### TODO Optional, but probably better to do all that in k8s later 